// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.2
// LVGL version: 8.2.0
// Project name: octo_nail

#ifndef _OCTO_NAIL_UI_H
#define _OCTO_NAIL_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"
extern lv_obj_t *ui_home_;
extern lv_obj_t *ui_tempArc1;
extern lv_obj_t *ui_actualLabel;
void ui_event_targetAKAsetpoint( lv_event_t * e);
extern lv_obj_t *ui_targetAKAsetpoint;
extern lv_obj_t *ui_targetLabel;
extern lv_obj_t *ui_actual;
void ui_event_power( lv_event_t * e);
extern lv_obj_t *ui_power;
void ui_event_buttonForGoingToSettings( lv_event_t * e);
extern lv_obj_t *ui_buttonForGoingToSettings;
void ui_event_octonailLabel( lv_event_t * e);
extern lv_obj_t *ui_octonailLabel;
extern lv_obj_t *ui_settings;
extern lv_obj_t *ui_Roller2;
extern lv_obj_t *ui_Spinner2;
extern lv_obj_t *ui____initial_actions0;






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
