// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.2
// LVGL version: 8.2.0
// Project name: octo_nail

#include "ui.h"

void ui_comp_temp_arc_create_hook( lv_obj_t * comp)
{
}

void ui_comp_temp_arc1_create_hook( lv_obj_t * comp)
{
}

void ui_comp_tempArc_create_hook( lv_obj_t * comp)
{
}
