// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.2
// LVGL version: 8.2.0
// Project name: octo_nail

#ifndef _OCTO_NAIL_UI_COMP_H
#define _OCTO_NAIL_UI_COMP_H

#ifdef __cplusplus
extern "C" {
#endif


lv_obj_t * ui_comp_get_child(lv_obj_t *comp, uint32_t child_idx);
extern uint32_t LV_EVENT_GET_COMP_CHILD;

// COMPONENT temp arc
#define UI_COMP_TEMP_ARC_TEMP_ARC 0
#define _UI_COMP_TEMP_ARC_NUM 1
lv_obj_t *ui_temp_arc_create(lv_obj_t *comp_parent);

// COMPONENT temp arc1
#define UI_COMP_TEMP_ARC1_TEMP_ARC1 0
#define _UI_COMP_TEMP_ARC1_NUM 1
lv_obj_t *ui_temp_arc1_create(lv_obj_t *comp_parent);

// COMPONENT tempArc
#define UI_COMP_TEMPARC_TEMPARC 0
#define _UI_COMP_TEMPARC_NUM 1
lv_obj_t *ui_tempArc_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
