// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.2
// LVGL version: 8.2.0
// Project name: octo_nail

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void getNewSetpoint(lv_event_t * e);
void runDaPID(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
